---
auth0_application_name: test_application
auth0_connection_name: test-database
auth0_token_dir: /tmp/auth0_token
auth0_uri: "https://{{auth0_domain}}/api/v2"
auth0_audiance: "{{auth0_uri}}/"
rds_instance_db_name: dpr_db
rds_instance_user: dbuser
rds_instance_password: dbpass123
rds_instance_name: dpr-rds
s3_bucketname: myawesomebucket12345432133
app_debug: False
virtualenv_path: /tmp/zappa_venv
dpr_api_path: /tmp/frictionlessdata/dpr-api
zappa_conf_path: "{{dpr_api_path}}/zappa_configuration-deploy.json"
dpr_api_git: https://github.com/frictionlessdata/dpr-api.git
zappa_app_name: dpr-api
