---
- debug: msg="token dir {{ auth0_token_dir }}"

- name: Create temp token directory
  file:
    path: "{{auth0_token_dir}}"
    state: directory
    mode: 0777

- name: Creating auth0 JWT token payload
  action: template src=auth0_jwt_payload.j2 dest="{{auth0_token_dir}}/conf.json"

- name: Generate auth0 Token
  command: "python ./auth0_token.py {{ auth0_token_dir }}"
  args:
    chdir: "{{ role_path }}/files"
  run_once: true

- name: Reading auth0 JWT token
  set_fact:
    auth0_jwt_token: "{{ lookup('file', auth0_token_dir + '/token') }}"

- debug: msg="Got token {{ auth0_jwt_token }}"

- name: Remove auth0 JWT temp files
  file:
    state: absent
    path: "{{auth0_token_dir}}"
