---
- name: Generate infra and application values
  action: template src=all_facts.j2 dest={{ role_path }}/files/all_facts.json

- name: Read infra and application values
  shell: cat {{ role_path }}/files/all_facts.json
  register: result_read

- debug: msg="{{result_read.stdout}}"
