---

- name: Create virtual environmane directory
  file:
    path: "{{ virtualenv_path }}"
    state: directory
    mode: 0755

- name: Create dpr api directory
  file:
    path: "{{ dpr_api_path }}"
    state: directory
    mode: 0755

- name: Install zappa
  pip:
    name: zappa
    version: 0.31.0
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: python2.7

- name: Creating virtual environment source script
  action: template src=venv_exec.j2 dest={{ virtualenv_path }}/exec mode=755

- name: Creating Zappa config template
  action: template src=zappa.j2 dest={{ zappa_conf_path }}

- name: Deploy zappa application.
  command: "{{ virtualenv_path }}/exec zappa undeploy stage -s {{ zappa_conf_path }} -y --json chdir={{ dpr_api_path }}"
  register: zappa_undeploy
  ignore_errors: True

- debug: msg="{{ zappa_undeploy }}"
