---
- name: Create zappa config directory
  file:
    path: "{{ zappa_config_dir }}"
    state: directory

- name: Generate zappa application name
  set_fact:
    zappa_project: "{{project}}-{{zappa_instance_number}}"
    zappa_local_conf_file: "{{ zappa_config_dir }}/{{ item }}_{{zappa_conf_file}}"

- name: Creating Zappa config template
  action: template src=zappa.j2 dest={{ zappa_config_dir }}/{{ item }}_{{zappa_conf_file}}

- debug:
    msg: "{{lookup('file',zappa_local_conf_file) }}"
  when: "{{app_debug}} == True"
