---
- name: Remove DPR-API directory
  file:
    state: absent
    path: "{{ dpr_api_path }}"

- name: Clone DPR-API
  git:
    repo: "{{ dpr_api_git }}"
    dest: "{{ dpr_api_path }}"

- name: Initiate submodule
  command: "git submodule update --init --recursive chdir={{ dpr_api_path }}"

- name: Checkout Branch
  command: "git checkout {{ submodule_branch }} chdir={{ dpr_api_path }}/{{submodule_path}}"

- name: Update Branch
  command: "git pull origin {{ submodule_branch }} chdir={{ dpr_api_path }}/{{ submodule_path }}"

- name: Creating dpr js .env file
  action: template src=dpr_js_env.j2 dest="{{ dpr_api_path }}/{{ submodule_path }}/.env"

- name: Install npm dependencies
  command: "npm install chdir={{ dpr_api_path }}/{{ submodule_path }}"

- name: Create Bundle
  command: "npm run build chdir={{ dpr_api_path }}/{{ submodule_path }}"

- name: Removing dpr-js
  command: "rm -rf {{ dpr_api_path }}/{{ submodule_path }}"

- name: Create virtual environmane directory
  file:
    path: "{{ virtualenv_path }}"
    state: directory
    mode: 0755

- name: Install zappa requirements
  pip:
    requirements: "{{ dpr_api_path }}/requirements.txt"
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: python2.7

- name: Creating virtual environment source script
  action: template src=venv_exec.j2 dest={{ virtualenv_path }}/exec mode=755
