---
- name: Create rds instance
  rds:
    command: create
    size: 5
    db_engine: postgres
    region: "{{ aws_region }}"
    publicly_accessible: yes
    wait: yes
    wait_timeout: 900
    instance_name: "{{ rds_instance_name }}"
    instance_type: db.t2.micro
    db_name: "{{rds_instance_db_name}}"
    username: "{{rds_instance_user}}"
    password: "{{rds_instance_password}}"
    aws_access_key: "{{aws_key}}"
    aws_secret_key: "{{aws_secret}}"

- name: Get RDS facts
  rds:
    command: facts
    region: "{{ aws_region }}"
    instance_name: "{{ rds_instance_name }}"
    aws_access_key: "{{aws_key}}"
    aws_secret_key: "{{aws_secret}}"
  register: rds

- debug: msg="Created RDS instance with endpoint- {{ rds.instance.endpoint }}"
