---
- name: Create S3 bucket
  s3:
    aws_access_key: "{{aws_key}}"
    aws_secret_key: "{{aws_secret}}"
    bucket: "{{ s3_bucketname }}"
    mode: create
    region: "{{ aws_region }}"

- debug: msg="Created s3 bucket with name- {{ s3_bucketname }}"
