---
- name: Dump all vars
  action: template src=dumpall.j2 dest=/tmp/ansible.all

- name: Generate infra and application values
  action: template src=info.j2 dest={{ role_path }}/files/info.json

- name: Read infra and application values
  shell: cat {{ role_path }}/files/info.json
  register: result_read

- name: Read infra and application values from json
  set_fact:
    app_info: "{{result_read.stdout | from_json}}"

- name: Print Application Info
  debug: msg="{{ app_info | to_nice_json(indent=2) }}"
