---
- hosts: localhost
  vars_prompt:
  - name: auth0_global_api_key
    prompt: System Property Mandetory - Plz provide auth0 API KEY
    default: yPO5f03axaTdh5JgaAj1HjRSu8VuHY8h
    private: no
  - name: auth0_global_secret
    prompt: System Property Mandetory - Plz provide auth0 Global secret KEY
    default: Zo4DcpFO_XYuAkxj1BTBw2ljdKVMsIsY37LGriE7RVTnQOnf5WBF8PF2kj_s0Qgy
    private: no
  - name: auth0_domain
    prompt: System Property Mandetory - Plz provide auth0 Domain name i.e. subhankarb.auth0.com
    default: atomatic.auth0.com
    private: no

  - name: aws_key
    prompt: System Property Mandetory - Plz provide AWS key
    default: AKIAJ3WYMOYMQTWX6RIQ
    private: no
  - name: aws_secret
    prompt: System Property Mandetory - Plz provide AWS secret key
    default: ZFjPdoOju1OKhK2Mz/4cDftyAj/Z0ffoMVIxynIO
    private: no
  - name: aws_region
    prompt: System Property Mandetory - Plz provide AWS zone name
    default: us-west-2
    private: no
  - name: domain_name
    prompt: System Property Mandetory - Plz provide route 53 domain name.
    default: staging.datapackag.com
    private: no

  roles:
    - common
    - deploy
