---

- name: get all clients
  uri:
   url: "{{auth0_uri}}/clients"
   method: GET
   HEADER_Authorization: "Bearer {{auth0_jwt_token}}"
   HEADER_Content-Type: application/json
   body_format: json
   status_code: 200
  register: get_clients

- name: Filter existing clients based on name
  set_fact:
    exists_clients: "{{ get_clients['json'] | selectattr('name', 'equalto', auth0_application_name) | map(attribute='client_id') | list }}"

- name: Print Existing clients
  debug:
    msg: "{{ exists_clients }}"
  when: "{{app_debug}} == True and {{exists_clients | length}} > 1"

- name: Delete existes clients with same name if more than one client with same name
  uri:
    url: "{{auth0_uri}}/clients/{{item}}"
    method: DELETE
    HEADER_Authorization: "Bearer {{auth0_jwt_token}}"
    HEADER_Content-Type: application/json
    body_format: json
    status_code: 204
  with_items: "{{exists_clients}}"
  register: delete_clients
  when: "{{exists_clients | length}} > 1"

- name: Creating auth0 Create client payload
  action: template src=auth0_create_client.j2 dest="{{ role_path }}/files/auth0_create_client.json"

- name: get all clients
  uri:
   url: "{{auth0_uri}}/clients"
   method: GET
   HEADER_Authorization: "Bearer {{auth0_jwt_token}}"
   HEADER_Content-Type: application/json
   body_format: json
   status_code: 200
  register: get_clients

- name: Filter existing clients based on name
  set_fact:
    exists_clients: "{{ get_clients['json'] | selectattr('name', 'equalto', auth0_application_name) | map(attribute='client_id') | list }}"

- name: Create Auth0 client if no pre existing client
  uri:
   url: "{{auth0_uri}}/clients"
   method: POST
   body: "{{ lookup('file','auth0_create_client.json') }}"
   HEADER_Authorization: "Bearer {{auth0_jwt_token}}"
   HEADER_Content-Type: application/json
   body_format: json
   status_code: 201
  register: create_clients
  when: "{{exists_clients | length}} == 0"

- name: get all clients
  uri:
   url: "{{auth0_uri}}/clients"
   method: GET
   HEADER_Authorization: "Bearer {{auth0_jwt_token}}"
   HEADER_Content-Type: application/json
   body_format: json
   status_code: 200
  register: get_clients

- name: Generating auth0 facts
  set_fact:
    auth0_client_id: "{{ (get_clients['json'] | selectattr('name', 'equalto', auth0_application_name) | map(attribute='client_id') | list)[0] }}"
    auth0_client_secret: "{{ (get_clients['json'] | selectattr('name', 'equalto', auth0_application_name) | map(attribute='client_secret') | list)[0] }}"

- debug:
    msg:"{{ auth0_client_id}}, {{auth0_client_secret}}"
  when: "{{app_debug}} == True"

- debug:
    msg: "Create client with id {{auth0_client_id}} and secret {{auth0_client_secret}}"
  when: "{{app_debug}} == True"

- name: Creating auth0 Create Connection payload template
  action: template src=auth0_create_connection.j2 dest="{{ role_path }}/files/auth0_create_connection.json"

- name: Creating auth0 Update Connection payload template
  action: template src=auth0_update_connection.j2 dest="{{ role_path }}/files/auth0_update_connection.json"

- name: get all connections
  uri:
   url: "{{auth0_uri}}/connections"
   method: GET
   HEADER_Authorization: "Bearer {{auth0_jwt_token}}"
   HEADER_Content-Type: application/json
   body_format: json
   status_code: 200
  register: get_clients

- name: Filter existing clients based on name
  set_fact:
    exists_connections: "{{ get_clients['json'] | selectattr('name', 'equalto', auth0_connection_name) | map(attribute='id') | list }}"

- name: Create Auth0 Connection of Strategy Auth0
  uri:
    url: "{{auth0_uri}}/connections"
    method: POST
    body: "{{ lookup('file','auth0_create_connection.json') }}"
    HEADER_Authorization: "Bearer {{auth0_jwt_token}}"
    HEADER_Content-Type: application/json
    body_format: json
    status_code: 201,409
  when: "{{exists_connections | length}} == 0"

- name: Update Auth0 Connection of Strategy Auth0
  uri:
    url: "{{auth0_uri}}/connections/{{item}}"
    method: PATCH
    body: "{{ lookup('file','auth0_update_connection.json') }}"
    HEADER_Authorization: "Bearer {{auth0_jwt_token}}"
    HEADER_Content-Type: application/json
    body_format: json
    status_code: 409,200
  with_items: "{{exists_connections}}"
  when: "{{exists_connections | length}} == 1"

- name: Creating auth0 Grant Client access template
  action: template src=auth0_client_grant.j2 dest="{{ role_path }}/files/auth0_client_grant.json"

- name: Give client grant for api operation
  uri:
    url: "{{auth0_uri}}/client-grants"
    method: POST
    body: "{{ lookup('file','auth0_client_grant.json') }}"
    HEADER_Authorization: "Bearer {{auth0_jwt_token}}"
    HEADER_Content-Type: application/json
    body_format: json
    status_code: 201, 409
