---
- name: "Create RDS db | {{ system_role }}"
  rds:
    region: "{{ region }}"
    command: create
    instance_name: "{{ project }}-{{ environment_tier }}-{{rds_suffix}}"
    instance_type: "db.{{ instance_type[system_role] }}"

    db_engine: "{{ rds_engine }}"
    upgrade: yes

    port: "{% if rds_engine == 'postgres' %}5432{%elif rds_engine == 'MySQL' %}3306{% endif %}"
    db_name: "{{ rds_database_name }}"
    username: "{{ rds_database_username }}"
    password: "{{ rds_database_password  | mandatory }}"

    backup_retention: "{{ rds_database_backup_retention }}"
    size: "{{ rds_database_size }}"
    wait: yes
    wait_timeout: 1500
  register: rds_instance_data
