---

- name: "Create S3 bucket| {{ system_role }}"
  s3_bucket:
    region: "{{ region }}"
    name: "{{ bit_store_bucket_name }}"
  register: s3_bucket_result
  failed_when:
    - "'failed' in s3_bucket_result and 'already own it' not in s3_bucket_result['msg']"


- debug:
    msg: "Created s3 bucket with name - {{ bit_store_bucket_name }}"
  when: "{{app_debug}} == True"
